name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Windows Installer
        run: |
          jpackage `
            --input target `
            --main-jar yapmc-1.0-SNAPSHOT.jar `
            --main-class com.overzealouspelican.Main `
            --name YAPMC `
            --type exe `
            --app-version 1.0.0 `
            --vendor "YAPMC" `
            --description "Privacy-focused desktop API client" `
            --java-options '-Xmx512m' `
            --win-dir-chooser `
            --win-menu `
            --win-shortcut

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: YAPMC-1.0.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create macOS Installer
        run: |
          jpackage \
            --input target \
            --main-jar yapmc-1.0-SNAPSHOT.jar \
            --main-class com.overzealouspelican.Main \
            --name YAPMC \
            --type dmg \
            --app-version 1.0.0 \
            --vendor "YAPMC" \
            --description "Privacy-focused desktop API client" \
            --java-options '-Xmx512m' \
            --mac-package-name YAPMC

      - name: Upload macOS Installer
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: YAPMC-1.0.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Linux DEB Installer (with jlink workaround)
        run: |
          # Try jpackage without --runtime-image first (let it use jlink)
          jpackage \
            --input target \
            --main-jar yapmc-1.0-SNAPSHOT.jar \
            --main-class com.overzealouspelican.Main \
            --name yapmc \
            --type deb \
            --app-version 1.0 \
            --vendor "YAPMC" \
            --description "Privacy-focused desktop API client" \
            --java-options '-Xmx512m' \
            --linux-package-name yapmc \
            --linux-app-category utils \
            --linux-shortcut && echo "jpackage succeeded" || {
            echo "jpackage with jlink failed, trying with custom runtime..."
            
            # Create a custom runtime by copying the full JDK
            cp -r $JAVA_HOME custom-runtime
            
            # Retry jpackage with the custom runtime
            jpackage \
              --input target \
              --main-jar yapmc-1.0-SNAPSHOT.jar \
              --main-class com.overzealouspelican.Main \
              --name yapmc \
              --type deb \
              --app-version 1.0 \
              --vendor "YAPMC" \
              --description "Privacy-focused desktop API client" \
              --java-options '-Xmx512m' \
              --runtime-image custom-runtime \
              --linux-package-name yapmc \
              --linux-app-category utils \
              --linux-shortcut
          }

      - name: Upload Linux Installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: yapmc_1.0-1_amd64.deb

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-installer/YAPMC-1.0.exe
            macos-installer/YAPMC-1.0.dmg
            linux-installer/yapmc_1.0-1_amd64.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
